# Generated by Django 4.0.2 on 2022-02-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=5000)),
                ('uuid', models.CharField(max_length=10)),
            ],
        ),
    ]
